### ISSUE TITLE
gráficos en dashboard

### ISSUE THREAD

**Issue by RosarioMolina** [CamilaAlvarez/IndicadoresDCC#1]
Al ir a la opción "ver todos los gráficos" no debería mostrar TODOS los gráficos existentes a ese nivel, y los de niveles inferiores dependientes?? Por ejemplo, en el dashboard de DCC-operación sólo se muestra 1 gráfico cuando aprieto "ver todos los gráficos", pero sus áreas tienen más

**Comment by CamilaAlvarez** [comment]
segun tengo entendido se muestran todos los graficos que han sido configurados para ese dashboard. 

Al final el mostrar todos, lo que hace es mostrar los graficos que han sido configurados, pero que el director a decidido no mostrar.

Tal vez @ibachman sepa mas de esto, por lo menos yo lo entendi asi

**Comment by CamilaAlvarez** [comment]
lo otro es que no se muestran graficos de metricas sin mediciones

**Comment by alopezq** [comment]
como dice camila esto no es un issue solo hay que configurarlo cada dashboard es una configuracion por separado. esto no es un error

**Comment by RosarioMolina** [comment]
No se si entiendo bien la diferencia entonces entre los gráficos que se muestran por default, y que más debería aparecer cuando uno va a la opción “mostrar todos”. Me lo podrían explicar?

**Comment by CamilaAlvarez** [comment]
cuando configuras un grafico hay un checkbox que indica si se va a mostrar en el dashboard o no.

Mostrar todos muestra todos los graficos que han sido configurados, tengan el checkbox marcado o no

**Comment by RosarioMolina** [comment]
En tal caso estoy teniendo problemas, por ejemplo, en el dashboard dcc-operaciones, no me muestra todos los gráficos que están sin el checkbox macado, a no ser que vaya a configuración, haga el check, luego un uncheck, y de ahí me aparecen en el dashboard .

**Comment by CamilaAlvarez** [comment]
es porque esos graficos no habian sido configurados antes. De nuevo, para mostrar los graficos, estos tienen que haber sido configurados, no se muestran por default

Cuando vas a la configuracion haces check y luego uncheck los estas configurando
