### ISSUE TITLE
logout

### ISSUE THREAD

**Issue by alopezq** [CamilaAlvarez/IndicadoresDCC#10]
Al hacer click en logout redirige a cualquier lado.
hay que crear la funcion para limpiar sesion y redirigir al login

**Comment by farodrig** [comment]
Creo que esto debería estar listo, al menos básicamente. Revisalo si puedes.

**Comment by alopezq** [comment]
funciona perfecto

**Comment by ekauffmann** [comment]
en la versión que hay ahora en orion el error continúa (tira error 404)

**Comment by CamilaAlvarez** [comment]
hay un problema en el logout para la pantalla de validacion

**Comment by farodrig** [comment]
Esto sigue abierto?? no me sale ningun error al hacer logout. No sé si ya se arregló o q.

**Comment by CamilaAlvarez** [comment]
Si, hay que cerrarlo no mas
