### ISSUE TITLE
Agregar unidades

### ISSUE THREAD

**Issue by CamilaAlvarez** [CamilaAlvarez/IndicadoresDCC#11]
Agregue una unidad con nombre = ' en el area computadores, y no puedo borrarla

**Comment by farodrig** [comment]
Es una wea del javascript el hecho q no lo puedas eliminar, pero eliminaré la posibilidad de agregar cosas asi y me ahorro modificar el javascript xD.

**Comment by farodrig** [comment]
Segun yo, esta arreglado.
