### ISSUE TITLE
Foto header de udashboard

### ISSUE THREAD

**Issue by alopezq** [CamilaAlvarez/IndicadoresDCC#14]
Esto se fijo el cliente:
"el recuadro del logo es de fondo blanco mientras que el header tiene un degrade gris"

si le hacen zoom se nota el rectangulo blanco

![degrade](https://cloud.githubusercontent.com/assets/5612408/7838097/70e9638c-0461-11e5-8a73-c251e9cfd5d4.PNG)

**Comment by CamilaAlvarez** [comment]
Ok xD

**Comment by farodrig** [comment]
Si lo había notado. El punto es q el logo debería tener fondo transparente, no blanco. Alguien sabe arreglar eso?? (no sé de photoshop o cosas con imágenes).

**Comment by CamilaAlvarez** [comment]
listo
