### ISSUE TITLE
feedback luis (aux)

### ISSUE THREAD

**Issue by alopezq** [CamilaAlvarez/IndicadoresDCC#15]
"
Hola Agustin,

Creo que la plataforma esta bastante bien y demuestra el avance que han
tenido. Creo que el trabajo fue grande y quizás sea buena idea dejar
presente que hubieron cambios afectaron algunos componentes o que serán
abordados en la siguiente iteración. Tengo algunas cosas chicas que
podrían ver si es necesario arreglarlas o simplemente
aclararlas/justificarlas durante la presentación.
Me imagino que la teste debería tener algunos de mis comentarios ya
reportados o sugeridos al equipo de trabajo.

Te envio mis comentarios luego de testear la plataforma (la revisión lo
hice en forma secuencia y luego me di cuenta que algunas cosillas se
podían resolver desde configuración).

0) Creo que seria buena idea poner una leyenda del significado de los
colores de las barras: Color azul-departamento, color naranja-areas de
operación?, color verde-areas de soporte?
Operación y soporte son áreas? Los elementos dentro de un "area" (por
ejemplo pregrado) son unidades? :)

1) Tengo mis dudas sobre la ventana de inicio de u-dashboard (luego de
login). Qué diferencia existe entre el icono de "Inicio" y el icono de
"operaciones". Ambas vistas dirigen a (icono inicio)/operaciones. Se pide
revisar porque da la impresión que es un bug que dirige a una sola vista.

2) Operaciones:
BARRA DCC: No me parece muy intuitivo que la barra azul "DCC" de la
impresión de que se trata de métricas del departamento del DCC. Me imagino
que podríamos ser mas explícitos "Metricas del DCC"? Cuando se sobrepone
el puntero sobre "DCC" el cambio de color me agrada.
-Cuando añado una metrica en "LA" no queda validado que se pueda ingresar
numero negativos, esta contemplado este caso? Pueden ver que añadí numero
negativos para año 2010 y todo se ve bien!!! Debería pasar esto?
-Cual es la cota superior e inferior para seleccionar año? Quise poner año
2020 o 2000, al -parecer no había error, ni siquiera me mando una alerta y
los datos nos e veían en el gráfico. Sugiero poner algun anuncio que el
año esta malo o algo por el estilo.

BARRA PREGRADO Y POSTGRADO: Los cambios de color en la barra "Pregrado" y
"Postgrado" no son evidentes como la barra "DCC". Sugiero cambiar de
color. Qué razón existe para que debajo de Pregrado y Postgrado se
mantenga "operación". me imagino que el cambio de color puede ser en toda
la barra como la del "DCC".
En ambas barras cuando quiero añadir datos me despliega información de
"pregrado" y además del "DCC", es decir puedo editar desde esta vista las
métricas del DCC. Esto es correcto?
Además luego em di cuenta que había una métrica Camila y luego de darle un
valor random apareció en vista DCC. Lo mismo para con postgrado.

3) Soporte:

Me imagino que esto estará listo para después porque no logre añadir
alguna métrica "ni siquiera "Camil", no pude añadir datos y no pude
desplegar ninguna visualización.

4) En general se ve bien y pienso que debería ir en este orden el menú
lateral.
-Inicio
-Operaciones
-Soporte

AHHHHHHH JAAAAA

En configuración se puede hacer muchas cosas que quizás responden a mis
observaciones.
Quice añadir una metrica a Camila en "Soporte" y aunque me dice que se ha
hecho con éxito no lo puedo ver.

El link "validar" hace algo?, porque quise validar la métrica pero no hay
ningún mensaje y cuando vuelvo a cargar "validar" sigue esperando
validación. :)

Creo que eso es todo.
Les pido que hagan un caso de prueba bien armado para evitar errores y si
algo esta incompleto siempre es buena idea decirlo durante la
presentación. El profesor se va a poner muy creativo con las preguntas.

Saludos,
Luis.
"

**Comment by CamilaAlvarez** [comment]
cambie de orden los botones. Coloco una leyenda sobre el indice?

**Comment by alopezq** [comment]
no me tinca, al menos a mi

**Comment by CamilaAlvarez** [comment]
Para mi es bastante claro como esta

**Comment by CamilaAlvarez** [comment]
El resto de los comentarios tienen que ver con el conocimiento que debera tener el director del sistema
