### ISSUE TITLE
errror de permisos

### ISSUE THREAD

**Issue by alopezq** [CamilaAlvarez/IndicadoresDCC#16]
Si estoy con user admin y aparece bajo su nombre administrador y hago click en configurar me pasa a usuario vizualizador y del header me saca las opciones config y validar

**Comment by CamilaAlvarez** [comment]
Solucionado, pero se genera otra issue relacionada [#18](https://github.com/CamilaAlvarez/IndicadoresDCC/issues/18)

**Comment by ekauffmann** [comment]
en la version que está en orion ahora, el usuario por default es Encargado... cuando hago click en validar el rol cambia a visualizador.

**Comment by ekauffmann** [comment]
ignórenme
