### ISSUE TITLE
Barra fea cuando no hay permisos para ver dashboard

### ISSUE THREAD

**Issue by CamilaAlvarez** [CamilaAlvarez/IndicadoresDCC#17]
![issue](https://cloud.githubusercontent.com/assets/6026021/7852049/1abe79ee-04ce-11e5-99b2-92af0cc13eeb.png)

**Comment by alopezq** [comment]
ver si se arreglo porfavor y cerrar

**Comment by CamilaAlvarez** [comment]
corregido
