### ISSUE TITLE
Cuantos roles poner bajo el nombre de usuario en las vistas

### ISSUE THREAD

**Issue by CamilaAlvarez** [CamilaAlvarez/IndicadoresDCC#18]
Si se ponen todos se ve muy feo. Ponemos el maximo rol, y le damos la opcion al usuario de revisar sus roles en una vista aparte?

**Comment by CamilaAlvarez** [comment]
Por ultimo debajo del usuario poner encargado de unidad, y en otra vista listar de que unidades

**Comment by alopezq** [comment]
yo pondria el permiso de mas alto nivel y chao

**Comment by CamilaAlvarez** [comment]
Es que el problema va con las personas que son encargados y visualizadores, porque segun su rol no deberia poder ver cosas. 

Al final seria un encargado raro. 

Dejemoslo abierto y lo conversamos con el cliente

**Comment by CamilaAlvarez** [comment]
Por ahora pondre permiso mas alto

**Comment by alopezq** [comment]
ok, ahi le preguntamos

**Comment by ekauffmann** [comment]
según el cliente tiene que ser de la siguiente manera:
-Diferenciar entre Director, Encargado (da lo mismo la unidad), Asistente de finanzas (da lo mismo la unidad) , Asistente unidad (da lo mismo qué unidad), Asistente del DCC y Visualizador
-En caso de múltiples roles, mostrar el de mayor rango
