### ISSUE TITLE
en el path algunas palabras salen sin mayúscula en la primera letra

### ISSUE THREAD

**Issue by ekauffmann** [CamilaAlvarez/IndicadoresDCC#19]
![bug_path](https://cloud.githubusercontent.com/assets/8388302/7866814/3a68f8bc-0548-11e5-9e55-2394016f59e1.PNG)

**Comment by ekauffmann** [comment]
![bug_path2](https://cloud.githubusercontent.com/assets/8388302/7867076/118c1a94-054a-11e5-984f-495e0b8be791.PNG)

**Comment by CamilaAlvarez** [comment]
listoco
