### ISSUE TITLE
Los modelos no pueden tener HTML

### ISSUE THREAD

**Issue by alopezq** [CamilaAlvarez/IndicadoresDCC#2]
Metrics_models.php contiene html

ejemplo ver funcion getAllMetrics()

**Comment by alopezq** [comment]
@fmosso

**Comment by ekauffmann** [comment]
cómo sé si puedo cerrar esta issue o no? xD

**Comment by farodrig** [comment]
Según yo, tendría q responder el q lo inició (Agustín) o al q se lo asignaron (Asumo que se lo asignaron a el fabian dado q el agustin lo nombró)

**Comment by alopezq** [comment]
abria que revisar modelo por modelo que no tuviera html.
el modelo Metrics_model.php tiene html y si no me equivoco lo hizo @fmosso 
el resto ninguno tiene
