### ISSUE TITLE
Rectángulos de distinto tamaño en "Conf. áreas y unidades"

### ISSUE THREAD

**Issue by ekauffmann** [CamilaAlvarez/IndicadoresDCC#26]
![bug_visualizacion](https://cloud.githubusercontent.com/assets/8388302/7941620/effd530a-092e-11e5-96f9-87d8710d4efd.png)

**Comment by farodrig** [comment]
Esto no es la vista de configurar areas y unidades, sino el de agregar métricas. Haciendo la aclaración.

**Comment by farodrig** [comment]
Arreglado, por favor revisar para cerrar el issue.

**Comment by ekauffmann** [comment]
Revisado. Cumple
