### ISSUE TITLE
Al borrar unidad o área: Mensaje de advertencia

### ISSUE THREAD

**Issue by ekauffmann** [CamilaAlvarez/IndicadoresDCC#28]
Debe aparecer un mensaje de advertencia explicando que se borarrá toda la información contenida

**Comment by farodrig** [comment]
Se agregó. Me gustaría q lo vieran y dieran feedback si consideran q debiese ser de otra manera. Luego de eso, cierro el issue.

**Comment by ekauffmann** [comment]
en este momento dice 
 Precaución!! Al eliminar esta área se perderá toda la información asociada a esta.
Por favor tener cuidado de respaldar los datos que no quiera que sea pierdan.

Funciona bien, y estéticamente está muy bueno.

Me gustaría que dijera "Advertencia" en vez de precaución y sin signos de exclamación. 
"Advertencia
Al eliminar esta área/unidad también se perderán todos sus datos asociados. Se recomienda respaldar la información antes de llevar a cabo esta acción.

**Comment by farodrig** [comment]
Esperando revisión del mensaje actual.

**Comment by ekauffmann** [comment]
está bueno. Unas correcciones de ortografía y listo (Y)
![selection_001](https://cloud.githubusercontent.com/assets/8388302/8114865/e2a92186-104d-11e5-923a-7ffc29f340b6.png)

**Comment by ekauffmann** [comment]
acabo de hacer pull y esto ya está arreglado (Y)
