### ISSUE TITLE
Validación: caso borde varios directores

### ISSUE THREAD

**Issue by ekauffmann** [CamilaAlvarez/IndicadoresDCC#29]
es muy probable que haya más de un director. Hay que preocuparse del caso en que hay cambios que validar y hay 2 o más directores con la ventana de validación abierta. Primero valida/rechaza uno de los 2, y el segundo, al traatar de validar/rechazar la misma solicitud, mostar un mensaje de error, de que la operación no se puede hacer pues alguien más ya había solucionado la validación pendiente

**Comment by CamilaAlvarez** [comment]
Lo reabro para que lo testeen

**Comment by ekauffmann** [comment]
funcina perfecto !! TuT buen trabajo
