### ISSUE TITLE
Barra de largo infinito

### ISSUE THREAD

**Issue by alopezq** [CamilaAlvarez/IndicadoresDCC#3]
Si uno se va a configurar->configurar dashboard y clikea en alumnos destacados sale una barra infinita

en chrome, IE, firefox

**Comment by CamilaAlvarez** [comment]
A mi no se me ve la barra infinita :(
Alguien puede verificar si el problema esta solucionado?

**Comment by alopezq** [comment]
Descubrí el error es un tema de pantalla en mi oficina tengo una pantalla de "22 a 1920*1080
tonces el problema sale cuando expando el navegador a pantalla completa si achico la ventana no hay problema adjunto fotos que lo demuestran

ojo esto es drama del css 

hay plugins pa los browsers que te simulan resoluciones y tamaños de pantalla
https://chrome.google.com/webstore/detail/window-resizer/kkelicaakdanhinjdeammmilcgefonfh?hl=en

![buena](https://cloud.githubusercontent.com/assets/5612408/7802998/24126c54-031a-11e5-9643-d4db0482c0f6.PNG)
![error](https://cloud.githubusercontent.com/assets/5612408/7803000/266ba7c2-031a-11e5-818e-3e36135a0c8e.PNG)

**Comment by CamilaAlvarez** [comment]
es raro porque el css le da un tamaño en pixeles fijo

**Comment by farodrig** [comment]
A mi me pasa lo mismo que al agustín.

**Comment by CamilaAlvarez** [comment]
te lo puedo encargar?
El problema es que como no me pasa, no se como arreglarlo

**Comment by farodrig** [comment]
Creo haberlo arreglado, al menos en mi PC ahora se ven bien, no sé en el de los demás, por favor revisar.
Si se ve bien y no genera ningun problema, lo cerramos.

**Comment by alopezq** [comment]
funciona perfecto
