### ISSUE TITLE
Validación: caso borde, asistentes modificando misma métrica en mismo año

### ISSUE THREAD

**Issue by ekauffmann** [CamilaAlvarez/IndicadoresDCC#30]
Inicialmente el cliente propone ésto: "Para asistentes que proponen modificaciones/agregar/borrar en el mismo año y misma métrica, la persona que valida puede ver todas las solicitudes. Si acepta todas, solo se guarda el último cambio aceptado"

Si se ve muy complicado, hay que pensar en otro tipo de solución. Por favor avisar cuál, para discutirlo con el cliente

**Comment by fmosso** [comment]
Al validar 2 metricas iguales, se sobreescribe la anterior

**Comment by CamilaAlvarez** [comment]
Lo abro para que lo testeen

**Comment by ekauffmann** [comment]
funciona perfecto !!! muchas gracias :P
