### ISSUE TITLE
Interfaz de conf de áreas y unidades/conf de métricas

### ISSUE THREAD

**Issue by ekauffmann** [CamilaAlvarez/IndicadoresDCC#31]
en configuración, tanto en configurar áreas y unidades como en configurar métricas, se presentan primero las que pertenecen a soporte (verde) y luego las que pertencen a operación (amarillo).
El cliente quiere que primero se vean los de operación y después las de soporte. Y sería mejor aún si es que las separas, onda, con una línea divisoria en la misma interfaz

**Comment by farodrig** [comment]
Esto es lo que he hecho, te tinca?? algun comentario?? @ekauffmann 
![areas](https://cloud.githubusercontent.com/assets/6003654/8021264/2fe84586-0c6f-11e5-9be2-1044e8fe56e4.png)

**Comment by CamilaAlvarez** [comment]
segun yo se ve hermoso

el unico pero es que se ve como que el + pertenece a soporte. Yo cacho que si pones una linea sobre el se veria mas claro

**Comment by farodrig** [comment]
Dado q hay como un título no sé si debería sacar el subtitulo bajo cada área que dice si es de soporte u Operación.

**Comment by CamilaAlvarez** [comment]
Sacalo mejor

**Comment by ekauffmann** [comment]
varias cosas:
-ojo con el color, lo que hay originalmente es que las de soporte son verdes, y las de operación son naranjas.
-la cami tiene razón, mejor saca el subtítulo bajo cada área
-el signo + solito abajo da la impresión de que quieres agregar algo que no es ni soporte ni operación.... qué tan difícil es poner un signo más en cada sección? para soporte y para operación

**Comment by farodrig** [comment]
- Los colores son muy random en verdad...como estaba harcodeado inicialmente, dependía de cual estuviera primero en la base de datos, ahora los asocie por nombre pero me imaginé q los colores daban lo mismo, entonces no me importó mucho q color asociar con que. Dejaré los colores de orion, pero insisto q siempre fueron algo super random.
- Suponía q había q sacarlo, por eso pregunté para confirmar.
- Según yo, no debería significar dificultad alguna.

**Comment by CamilaAlvarez** [comment]
se me dieron vuelta los colores D:

**Comment by farodrig** [comment]
Si, sorry es que cuando hice el push se me fue el arreglar el tema de los colores xDDD

**Comment by CamilaAlvarez** [comment]
yo los di vuelta :)

**Comment by farodrig** [comment]
i know :)

**Comment by farodrig** [comment]
Esta es la de configuración de métricas. Algo que decir?? @ekauffmann @CamilaAlvarez 

![metricas](https://cloud.githubusercontent.com/assets/6003654/8028098/618124ce-0d7c-11e5-8069-3ad1d596c9fe.png)

**Comment by CamilaAlvarez** [comment]
lo veo bien :+1:

**Comment by ekauffmann** [comment]
super!
