### ISSUE TITLE
Error al clickear botón validar siendo usuario Encargado

### ISSUE THREAD

**Issue by ekauffmann** [CamilaAlvarez/IndicadoresDCC#32]
![bug_validar](https://cloud.githubusercontent.com/assets/8388302/7991294/91fc7308-0acd-11e5-8bd3-ab991781047a.png)

**Comment by fmosso** [comment]
Solucionado

**Comment by fmosso** [comment]
Solucionado

**Comment by fmosso** [comment]
Solucionado

**Comment by fmosso** [comment]
Solucionado

**Comment by fmosso** [comment]
Solucionado
