### ISSUE TITLE
Duda al agregar datos

### ISSUE THREAD

**Issue by CamilaAlvarez** [CamilaAlvarez/IndicadoresDCC#33]
En el formulario donde se cargan los datos existentes, supongamos que existe un dato si validar para el 2010.
Si selecciono ese año debe mostrarse:
    1. nada
    2. el último dato validado para ese valor

No se cual de los dos les parece mejor

**Comment by ekauffmann** [comment]
tu dices en el caso, por ejemplo, de 2 asistentes que quieren cambiar un mismo dato, uno después del otro? 
Por simplicidad (lógica, no sé cómo será en código) yo no dejaría que nadie más pudiera cambiar un dato sin validar. Sería mejor aún que dijera algo como "dato en espera de validación" y que quede bloqueado el campo.
Qué les parece?

**Comment by ekauffmann** [comment]
lo cerré sin querer... perdón

**Comment by CamilaAlvarez** [comment]
Es que segun yo eso limita a la aplicacion, y ademas le entrega mucha
informacion al usuario

**Comment by CamilaAlvarez** [comment]
Creo que deberiamos preguntarle al cliente

**Comment by alopezq** [comment]
camila no entiendo bien el problema.

---

En el formulario donde se cargan los datos existentes, supongamos que existe un dato siN validar para el 2010.
- quisite decir SIN?

Si selecciono ese año debe mostrarse:
1. nada
2. el último dato validado para ese valor

No se cual de los dos les parece mejor

---

Debería mostrar el ultimo dato validado para ese año.

**Comment by CamilaAlvarez** [comment]
ok, entonces modificare eso

**Comment by CamilaAlvarez** [comment]
modifique esto, pero no se si esta funcionando. Pueden revisarlo?

**Comment by ekauffmann** [comment]
funciona perfectamente :dancer:
