### ISSUE TITLE
Modificacion de datos y dashboard

### ISSUE THREAD

**Issue by CamilaAlvarez** [CamilaAlvarez/IndicadoresDCC#34]
Hace mucho tiempo, hablando con elisa, nos pareció raro que al modificar un dato saliese del grafico.

Como tuvimos que modificar la base de datos para la validacion, aproveche de cambiar esto, de manera tal que al modificar un dato (quedando con validacion pendiente) se muestre el ultimo valor validado, asi el resto de los usuarios no se enteran si hubo cambios en los datos hasta que sean validados.

Revisenlo por fa

**Comment by ekauffmann** [comment]
hice pull. Funciona perfecto. Incluso con el usuario nuevo. Gracias
