### ISSUE TITLE
Queries y mayúscula en el nombre de las tablas: hice pull y se me cae todo

### ISSUE THREAD

**Issue by ekauffmann** [CamilaAlvarez/IndicadoresDCC#36]
estoy en linux, hice pull y encontré que el .sql había cambiado, así que lo importé de nuevo en phpmyadmin, y ahora la app no me funciona pues las queries tienen mayúscula en la primera letra de las tablas. Qué hago?

**Comment by CamilaAlvarez** [comment]
Tienes que cambiar todos los nombres de las tablas a mano. Todo es culpa de
windows

**Comment by CamilaAlvarez** [comment]
En phpmyadmin
