### ISSUE TITLE
error en carpeta modelos de ultimo commit

### ISSUE THREAD

**Issue by alopezq** [CamilaAlvarez/IndicadoresDCC#39]
Dos errores
Primero por regla de codeigniter el nombre de los modelos la primera letra es obligatoriamente mayuscula y el resto obligatoriamente minuscula. Por lo tanto si suben este codigo a una maquina linux va a fallar. esto ya fue mencionado en #8 

Segundo hay dos archivos MetOrg_model.php y Metorg_model.php que hacen lo mismo y estan en el ultimo commit en git

OJO los que usan windows tengan muuuuucho cuidado con estos errores

![capture](https://cloud.githubusercontent.com/assets/5612408/8173632/f9044fa8-13a6-11e5-8e18-7bfac9bdc2fe.PNG)

**Comment by CamilaAlvarez** [comment]
Yo cambie el que tenia una mayúscula al medio, dejando solo Metorg
(justamente por #8). Honestamente no se porque sigue existiendo MetOrg

**Comment by CamilaAlvarez** [comment]
extrañamente no me aparece el archivo en mi arbol, y cuando hago un git status me dice que lo elimine, pero no me permite comitear el cambio

**Comment by CamilaAlvarez** [comment]
lo tuve que borrar a mano
