### ISSUE TITLE
se pueden poner años erroneos

### ISSUE THREAD

**Issue by alopezq** [CamilaAlvarez/IndicadoresDCC#4]
Si uno se va a configurar->configurar dashboard y clikea en alumnos destacados sale desde 2000 hasta 1999 ( esto lo hize yo )

en chrome, IE, firefox

**Comment by CamilaAlvarez** [comment]
Creo que arregle esto. Pueden revisarlo?

**Comment by alopezq** [comment]
ahora si se ponen graficar por ejemplo del desde el 2000 hasta el 2000 en alumnos destacados sale el siguiente error. solo sucede en configurar dashboard unidades
![error](https://cloud.githubusercontent.com/assets/5612408/7837932/7e90e7c2-0460-11e5-9520-bac7b63644b8.PNG)

**Comment by CamilaAlvarez** [comment]
Lo arreglo en la tarde

**Comment by CamilaAlvarez** [comment]
era un error estupido. Revisalo ahora por fa

**Comment by alopezq** [comment]
arreglado
