### ISSUE TITLE
Aplicación se cae al crear métrica con unidad de medida "%"

### ISSUE THREAD

**Issue by ekauffmann** [CamilaAlvarez/IndicadoresDCC#41]
![bug_unidad_medida](https://cloud.githubusercontent.com/assets/8388302/8268848/c9ad8d5e-1767-11e5-9002-844772989d7e.png)

**Comment by CamilaAlvarez** [comment]
Revisen lo que subi por fa

**Comment by ekauffmann** [comment]
ya no se cae. Tira mensaje de error (Y)
