### ISSUE TITLE
App se cae al querer configurar Dashboard áreas

### ISSUE THREAD

**Issue by ekauffmann** [CamilaAlvarez/IndicadoresDCC#42]
![bug_conf_areas](https://cloud.githubusercontent.com/assets/8388302/8268894/2c5d5e10-1769-11e5-8e40-33072d8ddec7.png)

**Comment by CamilaAlvarez** [comment]
Parece que dejo de explotar xD

**Comment by CamilaAlvarez** [comment]
se cae en el configurar dashboard DCC D:

**Comment by ekauffmann** [comment]
D: avísame para hacer pull y testear

**Comment by CamilaAlvarez** [comment]
ahora si

**Comment by ekauffmann** [comment]
funciona ! (Y)
