### ISSUE TITLE
Bug validación: Asistente cambia misma métrica y se puede visualizar sin que alguien valide

### ISSUE THREAD

**Issue by ekauffmann** [CamilaAlvarez/IndicadoresDCC#43]
Estoy probando con la base de datos en la oficina de Agustín. Agregué un dato en Docencia-> Alumnos Destacados e inmediatamente lo modifiqué y después de eso lo pude visualizar, sin que alguien lo validara

**Comment by CamilaAlvarez** [comment]
pudiste visualizar con los valores que habias ingresado, o con los antiguos?

**Comment by CamilaAlvarez** [comment]
segun yo ahora si :)

**Comment by ekauffmann** [comment]
perfecto cami ;) gracias !!

**Comment by ekauffmann** [comment]
volvió este bug

**Comment by RosarioMolina** [comment]
yo lo probe en safari y ahora funciona bien el caso que dices
