### ISSUE TITLE
app se cae al dejar en blanco un campo al modificar un dato

### ISSUE THREAD

**Issue by ekauffmann** [CamilaAlvarez/IndicadoresDCC#44]
![bug_modificarmetrica](https://cloud.githubusercontent.com/assets/8388302/8273275/9782b662-183c-11e5-9356-638deadcbd4e.png)
![bug_modificarmetrica2](https://cloud.githubusercontent.com/assets/8388302/8273276/9fc4360c-183c-11e5-84c4-656c7906cb5d.png)

**Comment by CamilaAlvarez** [comment]
intenta ahora

**Comment by ekauffmann** [comment]
gracias, ahora funciona. Cuando dejo un campo vacío, por default queda valor "0"
