### ISSUE TITLE
Si uno clikea validar arroja error

### ISSUE THREAD

**Issue by alopezq** [CamilaAlvarez/IndicadoresDCC#5]
OJOOOOOOOOOOOOOOOO
este error no aparece en orion porque yo comente una linea para que no apareciera
esta linea esta en partials/headers linea 27 <span class="badge"><?php //echo $validate;?></span>

esto se debe deber que al hacer click en validar el controlador que lo redirige a la vista no le pasa la variable validate

**Comment by CamilaAlvarez** [comment]
Solucionado. Por ahora se pasa una constante
