### ISSUE TITLE
error en javascript

### ISSUE THREAD

**Issue by alopezq** [CamilaAlvarez/IndicadoresDCC#6]
En vista configurar_dashboard.php

linea 299 y linea 304 son iguales y deberian ser disintas
una deberias ser: from = e.value;
la otra: to = e.value;

tambien hay un error en la linea 238 envez de onkeyup deberia ser onchange

----------------Ojala se entienda esta seccion------------------
En las lineas 292 y 293 se fija los valores from y to a 2000 el problema de esto es que si yo por vista solo modifico uno de ellos ya sea from o to, el otro continua en 2000 aunque en vista desplegue otro valor. Esto se arregla borrando estas lineas y poblando dichas variables con bd. El problmea de esto es que la validacion no la hace bien.
----------------Ojala se entienda esta seccion------------------

hay errores generales en todo el javascript en todas las vistas ya que hay mucho codigo duplicado

recomiendo ver que codigo es distinto y que es igual y separar al javascript en un .js y hacer un include. estilo header

**Comment by alopezq** [comment]
como consejo pueden usar el codigo: console.log(nombre de la variable); 

apretar f12 y poner la consola y ver en caliente si la variable esta opteniendo desde vista lo que desean. es decir si en vista cambian a 2012, en consola deberia imprimirlo

**Comment by alopezq** [comment]
me falto agregar que ademas cuando el JS arroja un alerto o un error ya sea por que estan mal los años o lo que sea. las variables deberian refrescarse. como esta escrito el codigo las variables no se refrescan es por eso que logre introducir el error.

**Comment by CamilaAlvarez** [comment]
Creo que arregle esto. Pueden revisarlo?

**Comment by alopezq** [comment]
aun no ver #4

**Comment by alopezq** [comment]
arreglado
