### ISSUE TITLE
Error en la validacion php

### ISSUE THREAD

**Issue by alopezq** [CamilaAlvarez/IndicadoresDCC#7]
esto viene tambien con el issue #6 ya que me dejo poner años erroneos y grabarlo y el backend lo dejo pasar. El error esta en el controlador dashboardconfig.php entre las lineas 327 y 333 que nunca se verifica que from sea menor a to.

**Comment by CamilaAlvarez** [comment]
Creo que arregle esto. Pueden revisarlo?

**Comment by alopezq** [comment]
aun no ver #4

**Comment by alopezq** [comment]
arreglado
